### ISSUE TITLE
[Fix] Revert back themes and text sheme

### ISSUE THREAD

**Issue by xerta555** [MediaArea/MediaInfo#951] opened 2024-11-13 14:28 UTC
Hi
With the last version 24.11.1, the dark theme has some drawbacks compared to the previous version (not 24.11 but the one before):

The dark and light themes have some problems compared with the previous version (not 24.11, but the one before): the file description text box no longer uses the Windows text colour, but a grey colour that I don't find very legible. The same problem applies to the light theme.

Also, the scroll bar looks like the one in Windows 11, even though I'm on Windows 10 and prefer the one in 10 to the one in 11, so it's not consistent.

The best thing would be to add an option in the interface for MediaInfo to use the colours and images defined at system level again, so that everyone is happy.

In my case, having a custom Windows theme: all this causes visibility problems whatever the predefined theme selected.

Thanks in advance.

My setup:
Windows 10 22H2

**Comment by xerta555** [comment] 2024-11-13 15:23
> Screenshot please. The dark theme was never changed since its implementation and its colours are from Embarcadero's VCL Styles and not manually selected. On the light theme, the text colour was never changed too and should be black while only the background was changed. Scrollbars are not implemented or controlled by MediaInfo's source code as well.

OK, so I guess the problem must lie with the VCL styles in this case?

Here's how it looks on Windows 10 using the ‘Use system setting’ option:
![image](https://github.com/user-attachments/assets/fd14b7a8-eb23-4955-9a9e-7b69f9440ce1)
Note the scrollbars design (Windows 11), the window borders (Windows 11 style on Windows 10 host), the text color which don't match Windows color anymore and background color which hurts my eyes as well as not being very legible, which may not look like it on the screenshot, but it is in real life.

Using the "Light" option:
![image](https://github.com/user-attachments/assets/c20a6741-b74b-49d9-91bf-07da799bf935)
Note the title bar background and color and scrollbars which are respected here
but not the file infos background color which don't use the Windows default one bcz it just use an 255, 255, 255 rgb img/color

Using the "Dark" option:
![image](https://github.com/user-attachments/assets/c35a8ea1-0888-427e-ad81-b0de023e7f48)
This option includes all the inconsistencies and defects of the ‘Use system setting’ option, as my Windows 10 is configured in dark mode.

The best thing, I think, would be to use the default settings of the host system, so as not to leave any imperfections that could lead to visibility problems in my case.

**Comment by cjee21** [comment] 2024-11-13 17:06
This is how MediaInfo 24.11.1 is supposed to look on both light and dark theme. When set to follow system setting, it is exactly the same as when setting to light or dark manually with the difference that it follows the light or dark app mode setting in the Windows settings app.

Regarding the dark theme, it is 100% VCL style. The colours and scrollbars can not be changed in code. I am not satisfied with the non-native title bar and lack of window shadows compared to the light mode as well. The background of light mode text view was changed to match the easy view background (249 ,249, 249) which is also used by many apps that do not use (255, 255, 255).

| | |
| - | - |
| <img width="647" alt="Screenshot 2024-11-14 003843" src="https://github.com/user-attachments/assets/a6d8bf0e-d584-459c-86a3-f20c8ea19f9b"> | <img width="641" alt="Screenshot 2024-11-14 003922" src="https://github.com/user-attachments/assets/f24c779d-21f3-4475-8c85-c4c521272902"> |
| <img width="636" alt="Screenshot 2024-11-14 003903" src="https://github.com/user-attachments/assets/785ccf8c-1644-40eb-8925-da1d6ff81ed6"> | <img width="645" alt="Screenshot 2024-11-14 003942" src="https://github.com/user-attachments/assets/1883ac14-2ec2-4ebd-b7db-02b3e3601acf"> |

For comparison, shown below is close to how native Windows apps should look like for both modes. This is what I am 100% satisfied with.

| | |
| - | - |
| <img width="469" alt="Screenshot 2024-11-14 005359" src="https://github.com/user-attachments/assets/c04a16b0-a281-4fc3-b7a6-5909175e9633"> | <img width="472" alt="Screenshot 2024-11-14 005447" src="https://github.com/user-attachments/assets/52d5dbf7-1dcb-43f6-8da4-4fef19f8db9f"> |
| <img width="467" alt="Screenshot 2024-11-14 005513" src="https://github.com/user-attachments/assets/833a0f7e-e343-4b16-979e-66ea61e1fd9b"> | <img width="483" alt="Screenshot 2024-11-14 005621" src="https://github.com/user-attachments/assets/4c1b36d1-dbf5-411c-bbf4-68fba1cb329c"> |

**Comment by cjee21** [comment] 2024-11-13 17:09
@JeromeMartinez any idea what is going on in https://github.com/MediaArea/MediaInfo/issues/951#issuecomment-2473934166? Seems some toolbar icons went missing too?

**Comment by JeromeMartinez** [comment] 2024-11-13 17:13
> Seems some toolbar icons went missing too?

No idea, they are there on my side.

**Comment by JeromeMartinez** [comment] 2024-11-13 17:32
> windowed mode application are not retained after MediaInfo has been closed and then reopened. I imagine this is yet another VCL-style bug.

It is never by default on any SDK as far as I know.
There is a [pending PR](https://github.com/MediaArea/MediaInfo/pull/903) for that.

**Comment by cjee21** [comment] 2024-11-13 17:40
@JeromeMartinez should we just reset the backgrounds of all the text views to VCL default which is `clWindow`? This way it will follow whatever colour that is defined in Windows as `clWindow`. This is (255, 255, 255) by default on Windows 11 and is the background colour of File Explorer etc.

**Comment by JeromeMartinez** [comment] 2024-11-13 17:42
> should we just reset the backgrounds of all the text views to VCL default which is clWindow? This way it will follow whatever colour that is defined in Windows as clWindow.

I am fine with that.

**Comment by JeromeMartinez** [comment] 2024-11-13 17:43
Maybe checking the actual color and if > 249 we set 249? So it is not too much white when white is the default and we keep other default values.

**Comment by xerta555** [comment] 2024-11-13 17:43
> @JeromeMartinez should we just reset the backgrounds of all the text views to VCL default which is `clWindow`? This way it will follow whatever colour that is defined in Windows as `clWindow`. This is (255, 255, 255) by default on Windows 11 and is the background colour of File Explorer etc.

And what's possible to do about the corners of the MediaInfo window which a Windows 11 style, that don't match on Windows 10 setup ?

**Comment by cjee21** [comment] 2024-11-13 17:46
> And what's possible to do about the corners of the MediaInfo window which a Windows 11 style, that don't match on Windows 10 setup ?

For scrollbars, window borders, title bar and colours of the dark mode, it is beyond my capabilities and require someone who can mess with VCL styles. I have no intention of learning more about VCL styles and prefer to learn Qt which has dark mode support by default without all these additional work.

**Comment by xerta555** [comment] 2024-11-13 17:51
> > And what's possible to do about the corners of the MediaInfo window which a Windows 11 style, that don't match on Windows 10 setup ?
> 
> For scrollbars, window borders, title bar and colours of the dark mode, it is beyond my capabilities and require someone who can mess with VCL styles. I have no intention of learning more about VCL styles and prefer to learn Qt which has dark mode support by default without all these additional work.

Would replacing VCL with QT fix all these problems and inconsistencies?

**Comment by JeromeMartinez** [comment] 2024-11-13 17:52
> Would replacing VCL with QT fix all these problems and inconsistencies?

We have a Qt version but we are far from ready for replacing the current GUI SDK with the Qt version.

**Comment by xerta555** [comment] 2024-11-13 18:00
> > Would replacing VCL with QT fix all these problems and inconsistencies?
> 
> We have a Qt version but we are far from ready for replacing the current GUI SDK with the Qt version.

OK, I can test the version if you need logs files.
Small question, maybe silly, but as there are no silly questions but only useful questions: what if all the SDKs were removed from MediaInfo to just use on the native Windows Form32 that many other applications use, could that make the development easier ?

**Comment by JeromeMartinez** [comment] 2024-11-13 18:01
> what if all the SDKs were removed from MediaInfo to just use on the native Windows Form32 that many other applications use, could that make the development easier ?

**Comment by JeromeMartinez** [comment] 2024-11-13 18:04
> what if all the SDKs were removed from MediaInfo to just use on the native Windows Form32 that many other applications use, could that make the development easier ?

Maybe, maybe not, some parts will be easier, some others will be harder. And there is a cost of migration, we are not ready to spend this time (so $) ourselves and our sponsors are not interested in sponsoring such dev (the dark mode and 64-bit versions were implemented by @cjee21 on his free time).

Patch welcome if someone is interested enough in that for spending his own time and/or $.

**Comment by cjee21** [comment] 2024-11-13 18:05
@JeromeMartinez still plan to migrate to Qt? Should I working on that? Not sure what to do there though. It is already good enough for my use.

I know the HTML viewer has to be improved and Graph view needs to be added. However I discovered that Qt does not yet have integration with system web engines. The only solution I have is to use Qt's built-in web engine (it's on a branch in my fork, renders HTML perfectly) but the issue is that it will make MediaInfo install size a few hundred MB.

**Comment by JeromeMartinez** [comment] 2024-11-13 18:10
> still plan to migrate to Qt?

Not at short term, and even not sure that we will switch if Embarcadero keep developing the VCL. You already see all the impact of changing only small parts of the UI, and the switch to Qt would be even more complicated, I am very reluctant to do that.

>  The only solution I have is to use Qt's built-in web engine (it's on a branch in my fork, renders HTML perfectly) but the issue is that it will make MediaInfo install size a few hundred MB.

It is a big issue for switching to Qt on Windows.
but it could be used for Linux (even if most Linux users have the WxWindows SDK... We also need to stop trying several SDKs and choose one...), so if you wish you can send patches for Qt too which may be used on Linux (so no extra size as we use the distro one).

**Comment by cjee21** [comment] 2024-11-13 18:12
> what if all the SDKs were removed from MediaInfo to just use on the native Windows Form32 that many other applications use, could that make the development easier ?

AFAIK, need write lots of code to even get a window if using C++. Also Windows does not have native dark mode support. That is why many parts of Windows is still white in dark mode. There is WinUI3 which can make beautiful WIndows 11 apps with mica material. This is used by Windows' built-in apps. However, there is no graphic form editor/designer for this.

This is from my findings, which may be incorrect. But in short, previously I have tried to find a way to make beautiful Windows apps using Visual Studio only but gave up after reading documentations before starting.

**Comment by cjee21** [comment] 2024-11-13 18:18
> It is a big issue for switching to Qt on Windows. but it could be used for Linux (even if most Linux users have the WxWindows SDK... We also need to stop trying several SDKs and choose one...), so if you wish you can send patches for Qt too which may be used on Linux (so no extra size as we use the distro one).

I will upstream that branch then so I don't have to maintain it. If it is okay on Linux then maybe the Ubuntu (and other distros not yet using Qt) GUI can be migrated to Qt. The current wxWidgets one isn't rendering HTML properly.

Maybe Qt will integrate with Edge WebView2 by the time MediaInfo decides to move from VCL.

**Comment by cjee21** [comment] 2024-11-13 18:30
FYI to those who not yet know, the screenshots in the bottom half of https://github.com/MediaArea/MediaInfo/issues/951#issuecomment-2474230287 are screenshots of the Qt version.

**Comment by JeromeMartinez** [comment] 2024-11-13 18:40
[build with background color change to clWindows](https://mediaarea.net/download/snapshots/binary/mediainfo-gui/20241113-2/MediaInfo_GUI_24.11.20241113_Windows.exe).

**Comment by xerta555** [comment] 2024-11-13 20:55
> [build with background color change to clWindows](https://mediaarea.net/download/snapshots/binary/mediainfo-gui/20241113-2/MediaInfo_GUI_24.11.20241113_Windows.exe).

This version works as i want (like before for the GUI), thanks for this try 👍🏻 
Don't hesitate to send another tests builds if necessary.

**Comment by JeromeMartinez** [comment] 2024-11-13 20:57
Closed by https://github.com/MediaArea/MediaInfo/pull/952.

**Closed by JeromeMartinez** 2024-11-13 20:57 UTC
