### ISSUE TITLE
Access Violation at adress

### ISSUE THREAD

**Issue by dkangel666** [MediaArea/MediaInfo#943] opened 2024-11-08 10:15 UTC
![Sans titre](https://github.com/user-attachments/assets/e7ed19a6-56d9-4feb-8b6c-52d41414cd26)
Windows 10 x64 V24.11
every time i launch a file identification, info are good but this message appear
back to 24.06 and ok

**Comment by cjee21** [comment] 2024-11-08 11:31
Screenshot does not look like Windows 11.

Also maybe it will be easier to reproduce the issue if there is more info such as what settings were changed from default if any.

**Comment by dkangel666** [comment] 2024-11-08 11:34
oups sorry it's windows 10
no change from default
i just install 24.11 and the problem begin. reinstall 24.06 problem gone

**Comment by lelik107** [comment] 2024-11-08 12:15
2 guys on the forum where I usually am report this issue. One of them has it on Windows 10 22H2 Professional x64 and another one has it on Windows 7 both 32 and 64 bit and he was confused maybe MediaInfo dropped the support of Windows 7. I run Windows 10 22H2 Enterprise x64 and haven't got this issue that's weird.

**Comment by cjee21** [comment] 2024-11-08 12:18
>I run Windows 10 22H2 Enterprise x64 and haven't got this issue that's weird.

I cannot reproduce on Windows 11 24H2 too. That's why need figure out what is different on the systems that are exhibiting this issue.

**Comment by JeromeMartinez** [comment] 2024-11-08 12:18
> maybe MediaInfo dropped the support of Windows 7.

You can confirm him that we don't drop (yet) the support of Windows 7.
I tested the changes from @cjee21 on Windows 7 before validating them and I paused the changes breaking the Windows 7 support.
This is not about Windows 7, or at least it was not expected. Let's try to fix the issue with win10/11 machines then we'll see if it is still present on win7.

**Comment by lelik107** [comment] 2024-11-08 12:26
@JeromeMartinez  Thank you, he sees it right now. And as for the issue I've tested on my 2-nd PC with Windows 10 22H2 Professional x64 and hasn't got it so we know now:
1. It is not like every user affected.
2. It doesn't depends on OS.

**Comment by cjee21** [comment] 2024-11-08 12:53
Can we get info about whether Microsoft Edge WebView2 Runtime is installed on the affected systems vs the not affected systems?

**Comment by JeromeMartinez** [comment] 2024-11-08 12:55
> Can we get info about whether Microsoft Edge WebView2 Runtime is installed on the affected systems vs the not affected systems?

How to check that?

**Comment by cjee21** [comment] 2024-11-08 12:56
> > Can we get info about whether Microsoft Edge WebView2 Runtime is installed on the affected systems vs the not affected systems?
> 
> How to check that?

It will be in the list of installed applications on Windows if installed. Check Installed apps section in Settings app or Control Panel.

**Comment by dkangel666** [comment] 2024-11-08 12:57
Microsoft Edge WebView2 Runtime is not installed in my pc

**Comment by lelik107** [comment] 2024-11-08 13:01
cmd - winget list webview2 for Windows 10 - Microsoft.EdgeWebView2Runtime 130.0.2849.56
And I have it on both PCs for the other guys I let you know.

**Comment by xerta555** [comment] 2024-11-08 13:31
Hi, i also confirm that i have this bug on last Windows 10 22H2 x64.
Same as @dkangel666 MS Edge components are not installed on my setup.

I also have checked the events log of Windows and fiability history, nothing related to MediaInfo.

**Comment by VictorVG** [comment] 2024-11-08 13:36
Win7 SP1 x86_64, not reproduction? but I found different in to .import section - also 24.11 required ADVAPI32
API-MS-WIN-CORE-WINRT-L1-1-0.DLL and API-MS-WIN-CORE-WINRT-STRING-L1-1-0.DLL and run double hidden resident's process MediaInfo.exe show in to Process Hacker:

![20241108_161705](https://github.com/user-attachments/assets/551061c7-327a-497c-92fb-8fdd1a38e52b)

for end this process required call TerminateProcess() or send command Terminate in Process Hacker

v24.06 not run this process...

**Comment by lelik107** [comment] 2024-11-08 14:05
@cjee21 That guy with Window 7 said he's got no WebView2.

**Comment by lelik107** [comment] 2024-11-08 15:25
@cjee21 That guy with Windows 10 22H2 Professional x64 clearly said: "I installed WebView2 and the error had gone."

**Comment by dkangel666** [comment] 2024-11-08 15:42
error gone too by installing webview2
thanks to everybody

**Closed** 2024-11-08 16:33 UTC

**Comment by lelik107** [comment] 2024-11-09 02:43
@JeromeMartinez  @cjee21
Dear developers I'd like to ask you these favors - if you fixed some bug and made some changes consider a re-upload, please, to the official site in some time with something like .2 added (24.11.2). I mean don't do this silently please - It's just easier for the usual users to tell them apart. And for Jerome especially: I see you wearing the glasses and so do I - 2 is just more clearly visible, then 1 (24.11.1).

**Comment by cjee21** [comment] 2024-11-09 07:06
> @JeromeMartinez @cjee21 Dear developers I'd like to ask you these favors - if you fixed some bugs and made some changes consider a re-upload, please, to the official site in some time with something like .2 added to the version, for example (24.11.2). I mean don't do this silently, please - It's just easier for the usual users to tell them apart. And for Jerome especially: I see you wearing the glasses and so do I - 2 is just more clearly visible, than 1 (24.11.1).

FYI the official developers are JeromeMartinez and g-maxime. I am just a volunteer outside collaborator with no ability to merge commits or create releases. I noticed a new 24.11.1 version has been published to be website and the built-in update checker is picking it up too.

**Comment by xerta555** [comment] 2024-11-09 17:30
I confirm that i don't the bug anymore with the new 24.11.1 version available on official website.
Thx for the work.
