### ISSUE TITLE
Access Violation with 24.11 version

### ISSUE THREAD

**Issue by tessa112** [MediaArea/MediaInfo#945] opened 2024-11-08 17:06 UTC
I get an access violation on all tested win7 systems.
Both 32 and 64-bit system throws the error every time i try to open a media file or quit the application.
All systems are updated with latest ESU updates.
This is using the 24.11 version without installer.

**Comment by JeromeMartinez** [comment] 2024-11-08 17:10
Maybe duplicate of #943.
Please test [this build](https://mediaarea.net/download/snapshots/binary/mediainfo-gui/20241108-4/MediaInfo_GUI_24.11.20241108_Windows_x64.exe).

**Comment by tessa112** [comment] 2024-11-08 17:39
That works, thanks !

I assume the unpleasing white background is due to that webview2 stuff, or is that by choice ?

![image](https://github.com/user-attachments/assets/8f1b4d27-ed3a-4b33-891e-45fc7d40b793)

**Closed** 2024-11-08 17:40 UTC

**Comment by VictorVG** [comment] 2024-11-08 19:11
[JeromeMartinez](https://github.com/JeromeMartinez)

I test [this build](https://mediaarea.net/download/snapshots/binary/mediainfo-gui/20241108-4/MediaInfo_GUI_24.11.20241108_Windows_x64.exe) on to Win7 SP1 x64 (also installed hot fix Windows6.1-KB2619497-v2-x64 needed fo Xeon E5 2697 v2 - then CPU have 12 core /24 tread and L3=30 Mb gt then kernel limit <= 8 core and L3 <= 16 Mb) in to include and exclude Graph plug-in - work success w/o AV at read adress 0x18 (Interrupt vectors arrea - access hardware protected).

**Comment by JeromeMartinez** [comment] 2024-11-10 12:29
> I assume the unpleasing white background is due to that webview2 stuff, or is that by choice ?

@tessa112 please test [this build](https://mediaarea.net/download/snapshots/binary/mediainfo-gui/20241109-3/MediaInfo_GUI_24.11.20241109_Windows.exe).

**Comment by tessa112** [comment] 2024-11-14 19:02
> @tessa112 please test [this build]

Sorry for late reply, this one works fine for me as well as the previous 241108 version.
Really appreciate the quick fix, however i will stay on the 24.06 version with the grey background.
