### ISSUE TITLE
The Win32 App UI Still Looks Blurred

### ISSUE THREAD

**Issue by Xashyar** [MediaArea/MediaInfo#289] opened 2018-09-28 00:39 UTC
I took a screenshot side to side with Word for comparison:
Version: 18.08.1
OS: Windows 10

![image](https://user-images.githubusercontent.com/34171942/46181705-31410480-c2d4-11e8-9b0c-332b25fd47b7.png)

**Comment by JeromeMartinez** [comment] 2018-09-28 08:49
I don't reproduce on a "low def" screen, I guess it is the automatic scaling on HiDef screen (made by Windows).
Our UI toolkit is old, we need to move away from it, it will not be soon :(.

BTW, thanks for all reports, appreciated.

**Comment by Revan654** [comment] 2018-09-28 18:59
User could try to calibrate the monitor first which could help. The GPU also plays a factor on how things like this are renders. There just way to many factors to take into account to be able to reproduce the issue.

------
On programming Side of things:

There are options like DPI aware, Which could be used if programming code / Version you use supports it. It scales based on the users DPI. Most have a DPI of 96.

---------

Not 100% sure how fonts are used and rendered within Mediainfo, If you can switch your Windows fonts and it changes font used in Mediainfo. Then that's one option you can try.

if not This requires Dev altering the code.

Maybe render the text with a different font or enable bold might help along with some AA(if needed). Usually Windows has Tahoma as there default font. Tahoma isn't as clear as other fonts like fonts from Serif family.

I found DejaVu Serif to be a very good font to use, it always comes out clear. Not sure if Windows includes that font as a default or not. I know Linux uses DejaVu Serif as there default font. Microsoft has there own version of Serif which comes with Windows.

**Comment by cjee21** [comment] 2024-05-29 05:34
Based on screenshot in first post, the user seems to be using a high DPI display at high Windows scaling. This issue should already be resolved by the recent high DPI patch.

Here is a screenshot of HTML view at 200% Windows scaling on a build from current master branch.
![Screenshot 2024-05-29 132639](https://github.com/MediaArea/MediaInfo/assets/77721854/03f01faf-36fd-4a14-93aa-c2c870c51bad)

**Comment by JeromeMartinez** [comment] 2024-05-29 05:46
#835.
[development snapshot](https://mediaarea.net/download/snapshots/binary/mediainfo-gui/20240529/MediaInfo_GUI_24.04.20240529_Windows.exe).

**Closed by JeromeMartinez** 2024-05-29 05:46 UTC
Labels: bug, enhancement
