### ISSUE TITLE
Version 0.94 and up are not able anymore to parse many MTS and M2TS without "freezing"

### ISSUE THREAD

**Issue by Sami32** [MediaArea/MediaInfo#155] opened 2017-05-18 23:07 UTC
At least on Windows XP SP3 32-bit. The GUI will not even open on some M2TS files (Atmos), but stay in the process task bar.
[00007.mts.txt](https://github.com/MediaArea/MediaInfo/files/1012631/00007.mts.txt)
http://www.alluc.ee/l/Dolby-ATMOS-Helicopter-m2ts/cqj7ctv0

This issue affect the GUI and the CLI version (wait for ever without returning the value asked) as well.

**Comment by JeromeMartinez** [comment] 2017-05-19 09:23
Confirmed with latest release, looks like OK with [latest snapshot](https://mediaarea.net/download/snapshots/binary/mediainfo-gui/), can you test with it?

**Comment by Sami32** [comment] 2017-05-19 12:45
Thank you for the snapshots link :sunglasses: 
The GUI is now fully responding.

But the field values are not throwed, it still waiting for ever.
The strange thing, for me, is that the GUI display all the informations, but the values requested from the CLI is never returned, ONLY for that kind of files...
In bref:
GUI :+1: 
CLI :-1:

**Comment by Sami32** [comment] 2017-05-20 13:31
Sorry, to be correct, i should have said **DLL** and not CLI, as i only tested the GUI from the latest snapshot. The DLL don't return the field values asked by a Java code, it hang out, "freeze".

**Comment by JeromeMartinez** [comment] 2017-05-20 13:51
> as i only tested the GUI from the latest snapshot. 

I don't understand: if you tested only the GUI with the latest snapshot, how can you say that DLL stil doesn't return? Did you test the DLL latest snapshot?

**Comment by Sami32** [comment] 2017-05-20 14:35
I used the latest DLL taken from the GUI latest snapshot, and copy it in our Java application folder.

**Comment by JeromeMartinez** [comment] 2017-05-20 14:36
And it still freezes, right?

**Comment by Sami32** [comment] 2017-05-20 14:36
Right, but only for some MTS and M2TS files.

**Comment by JeromeMartinez** [comment] 2017-05-20 14:37
Note that the GUI uses the DLL from the snapshot, it is weird that the GUI does not freeze and the DLL does.
Do you conform that the files you provides makes the DLL freezing, and not the GUI?

**Comment by Sami32** [comment] 2017-05-20 14:38
Yes. I found it strange as well.

**Comment by Sami32** [comment] 2017-05-20 21:10
OK, so after some more testing on that strange issue, for me, i discovered that the files affected was not the same after your latest GUI fix, except the MTS file already posted.
They was correctly parsed before, and the ones that wasn't are correctly parsed now.
Did that make any sens to you ? Perhaps your eagle eyes will see something in these files that could explain that.

[data0001.ts.txt](https://github.com/MediaArea/MediaInfo/files/1016510/data0001.ts.txt)
[AVS-HD720-PCM.m2ts.txt](https://github.com/MediaArea/MediaInfo/files/1016512/AVS-HD720-PCM.m2ts.txt) (Before it was the 1080-PCM that was freezing)

**Comment by JeromeMartinez** [comment] 2017-05-25 17:12
Should be fixed with [this commit](https://github.com/MediaArea/MediaInfoLib/commit/37ff6d99c0a897ac01994cde69f176e3a25699dd).
You can test with [snapshots](https://mediaarea.net/download/snapshots/binary/mediainfo-gui/).
reopen the ticket if you still get a problem.

**Closed by JeromeMartinez** 2017-05-25 17:12 UTC

**Comment by Sami32** [comment] 2017-05-25 17:29
Yes ! You did it :+1: 
Well done :smile:
