### ISSUE TITLE
MediaInfo and FFMpeg disagree on number of audio channels

### ISSUE THREAD

**Issue by RensvanderZwan** [MediaArea/MediaInfo#875] opened 2024-06-19 10:48 UTC
MediaInfo and FFMpeg dissagree on number of audiochannels.

For media file: [https://we.tl/t-rCoWScLZfC](https://we.tl/t-rCoWScLZfC) , MediaInfo says there are 9 audio channels (6 PCM and 3 Dolby-E) and FFMpeg says there are 8 audiochannels (by lack of a Dolby-E decoder all considers them as PCM).

There is something strange about the streamorder. All Doly-E channels are streamorder 5 and stream 6 is absent. So Streamorder is 0,1,2,3,4,5,5,5,7,8.

I am using MediaInfo to set parameters for FFMpeg conversion like audio channels , framerate conversion etc. The conversion fails because of this dissagrement

So who is right? Is there a 'Dark' audio channel?

MediaInfo=24.05.1 / FFMpeg=version 6.1.1-full_build-www.gyan.dev

**Comment by JeromeMartinez** [comment] 2024-06-19 10:52
Duplicate of https://github.com/MediaArea/MediaInfo/issues/874.

**Closed by JeromeMartinez** 2024-06-19 10:52 UTC
